# -*- coding: utf-8 -*-
"""TA Week 10 Session 1 Plot Exercise

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VPLb0qoW4IikiMAI1ZlEzwH5rjnCD5EI
"""

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

data = {'60':5, '65':8, '70':10,
        '75':15,'80':10, '85':12, '90':5,
        '95':7 ,'100':1}
courses = list(data.keys())
values = list(data.values())

fig = plt.figure(figsize = (10, 5))

# creating the bar plot
plt.bar(courses, values, color ='maroon',
        width = 0.4)

plt.xlabel("Score")
plt.ylabel("Amounts of Student")
plt.title("Computer Science Discrete Math Finals Exams")
plt.show()